name: XRP Auto Claim

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Auto-restart every 6 hours

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 357  # 5 hours, 57 minutes (just before auto-restart)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests rich

      - name: Run script
        run: python xrp.py
